### ISSUE TITLE
consider using {tsibble}

### ISSUE THREAD

**Issue by aspina7** [reconhub/incidence2#13]
hi - like the idea of moving this to cleaner syntax! 

Just thought I would suggest using tsibble to do some of the underlying legwork. There are yearweek and year* functions and all works pretty clean. 

The advantage over aweek is that is recognised as a date automatically. The disadvantage over aweek is that cannot (as of yet) set a different start day for a week. 

Actually just posted issues this morning on {[aweek](https://github.com/reconhub/aweek/issues/34)} and {[tsibble](https://github.com/tidyverts/tsibble/issues/205#issue-650391831)} about this. 

As a sidenote - while in the process of redoing everything might be worth considering renaming just to make certain epis happy and avoid semantic discussions around incidence vs incidence rate vs prevalence ([see](https://wiki.ecdc.europa.eu/fem/Pages/Incidence%20rate.aspx))

**Comment by tjtnew** [comment]
Cheers for the feedback - really useful!

* Re: tsibble - the "alpha alpha" version of incidence2 was actually built on top of tsibble. It is a really nice package! However because each row of inputs we deal with can be considered a unique observation there was little need for the `key` used in tsibble.  It felt like we were adding unnecessary dependencies for a small subset of the functionality.  At the stage with dplyr and tibble still refining how best to extend their functions/classes I'm wary of relying on an intermediate package in the implementation. Having said that we're definitely not unwilling to change.  The underlying implementation is such that we could swap out for tsibble in future if everyone felt that was the way to go!  

* In regards to aweek, tsibble is implemented in a way which lets you use the aweek package for grouping should you wish but I agree it would be a useful function to be implemented directly although it should maybe be something for the lubridate package as opposed to tsibble.  If it helps I can dig out my code that shows you how to use aweek with tsibble.

* On naming - I will definitely look in to that.  @thibautjombart and I were only discussing this morning how now was the time to change any names from the original package.

**Comment by aspina7** [comment]
> The underlying implementation is such that we could swap out for tsibble in future if everyone felt that was the way to go!

Fair - makes sense the tsibble key (while functional) has been a bit annoying at times! 

> If it helps I can dig out my code that shows you how to use aweek with tsibble.

oo yes please that would be awesome!

**Comment by tjtnew** [comment]
@aspina7  here you go.  Do you mind if I post this on `tsibble` as well in case others are interested?

``` r
library(outbreaks)
library(dplyr, warn.conflicts = FALSE)
library(tsibble)
library(aweek)
library(lubridate, warn.conflicts = FALSE)
library(vctrs)


# bits for tsibble --------------------------------------------------------
index_valid.aweek <- function(x) {
  TRUE
}

interval_pull.aweek <- function(x) {
  wk <- as.double((as_date(x) - as_date("1969-12-29")) / 7)
  nweeks <- tsibble:::gcd_interval(wk)
  new_interval(week = nweeks)
}

vec_cast.double.aweek <- function(x, to, ...) {
  as.double((as_date(x) - as_date("1969-12-29")) / 7)
}


# load data ---------------------------------------------------------------
dat_raw <- ebola_sim_clean$linelist

dat_ts <-
  dat_raw %>%
  as_tsibble(key = case_id, index = date_of_onset)


# aweek version - (epiweek with days floored to start of the week) --------
dat_ts %>%
  group_by(hospital, outcome) %>%
  index_by(Year_week = ~ date2week(., week_start = "Sunday", floor_day = TRUE)) %>%
  group_by(hospital, outcome) %>%
  summarise(count = n())
#> # A tsibble: 849 x 4 [1W]
#> # Key:       hospital, outcome [18]
#> # Groups:    hospital [6]
#>    hospital           outcome Year_week  count
#>    <fct>              <fct>   <aweek>    <int>
#>  1 Connaught Hospital Death   2014-W22-1     3
#>  2 Connaught Hospital Death   2014-W23-1     3
#>  3 Connaught Hospital Death   2014-W24-1     1
#>  4 Connaught Hospital Death   2014-W25-1     6
#>  5 Connaught Hospital Death   2014-W26-1     4
#>  6 Connaught Hospital Death   2014-W27-1     1
#>  7 Connaught Hospital Death   2014-W28-1     4
#>  8 Connaught Hospital Death   2014-W29-1     6
#>  9 Connaught Hospital Death   2014-W30-1     4
#> 10 Connaught Hospital Death   2014-W31-1    12
#> # … with 839 more rows


# aweek version - (epiweek with days not floored) -------------------------
dat_ts %>%
  group_by(hospital, outcome) %>%
  index_by(Year_week = ~ date2week(., week_start = "Sunday", floor_day = FALSE)) %>%
  group_by(hospital, outcome) %>%
  summarise(count = n())
#> # A tsibble: 3,051 x 4 [9.99999999917733e-07W]
#> # Key:       hospital, outcome [18]
#> # Groups:    hospital [6]
#>    hospital           outcome Year_week  count
#>    <fct>              <fct>   <aweek>    <int>
#>  1 Connaught Hospital Death   2014-W22-1     1
#>  2 Connaught Hospital Death   2014-W22-3     1
#>  3 Connaught Hospital Death   2014-W22-7     1
#>  4 Connaught Hospital Death   2014-W23-3     1
#>  5 Connaught Hospital Death   2014-W23-6     1
#>  6 Connaught Hospital Death   2014-W23-7     1
#>  7 Connaught Hospital Death   2014-W24-7     1
#>  8 Connaught Hospital Death   2014-W25-1     2
#>  9 Connaught Hospital Death   2014-W25-5     1
#> 10 Connaught Hospital Death   2014-W25-6     3
#> # … with 3,041 more rows
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aspina7** [comment]
awesome thanks! 
Nay dont mind at all - go for it

**Comment by aspina7** [comment]
hey @tjtnew just circling back to this, based on the other discussion above and the fix done over in tsibble. Worth switching incidence2 to use lubridate rather than aweek?

**Comment by tjtnew** [comment]
hey @aspina7 I was actually looking at this this, will summarise where I'm at below:
* I'm trying to work towards the v1.0 release of incidence2 and a major part of this is standardising how the intervals / date groups work.  Currently, only the week groupings (due to aweek) generate a proper s3 class that you can work with independently from the incidence dataframes.
* Short term my plan is to standardise all of the date groupings (week, month, quarter and year) and implement them with the [vctrs](https://vctrs.r-lib.org/) package.  This will mean I move away from `aweek` but may not necessitate using lubridate (my current rough implementation only uses the `wday` function from there which I think I can avoid by converting Dates to POSIXlt and getting the weekday from there).  The months and quarters groupings will then be implemented in a way similar to the implementation here https://github.com/DavisVaughan/datea.
* Longer term, it looks like Davis Vaughan is working on a very cool package called [clock](https://github.com/DavisVaughan/clock).  Once this is released I think all our date grouping functionality will be replaced by this.  It looks like it's going to be a really well thought out packages for dealing with dates and datetimes!
